{% set name = "magic_enum" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Neargye/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0ffc840d881a377a520e999b79ec2823b3b8ffadccad5d94084cc37fcf6fe2c9

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/magic_enum.hpp  # [unix]

about:
  home: https://github.com/Neargye/magic_enum
  summary: Header-only C++17 library provides static reflection for enums
  description: |
    Static reflection for enums (to string, from string, iteration) for modern C++,
    work with any enum type without any macro or boilerplate code
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Neargye/magic_enum

extra:
  recipe-maintainers:
    - versatran01
